import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  shell: { flex: 1, backgroundColor: '#f8fafc' },
  content: { flex: 1 },
  flex: { flex: 1, minWidth: 0 },
  centerScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14 },
  unlockScreen: { flex: 1, justifyContent: 'center', padding: 24, gap: 18 },
  lockIcon: {
    alignSelf: 'flex-start',
    width: 82,
    height: 82,
    borderRadius: 18,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitle: { color: '#0f172a', fontSize: 36, fontWeight: '800', letterSpacing: 0 },
  heroCopy: { color: '#475569', fontSize: 18, lineHeight: 27 },
  disclaimer: { color: '#64748b', fontSize: 13, lineHeight: 19 },
  onboarding: { padding: 24, gap: 16 },
  screen: { padding: 16, paddingBottom: 100, gap: 14 },
  header: { paddingTop: 8, paddingBottom: 6 },
  screenTitle: { color: '#0f172a', fontSize: 34, fontWeight: '800', letterSpacing: 0 },
  screenSubtitle: { color: '#64748b', fontSize: 15, marginTop: 3 },
  summaryCard: { backgroundColor: '#ffffff', borderRadius: 8, padding: 16, borderWidth: 1, borderColor: '#e2e8f0', gap: 16 },
  summaryHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  cardTitle: { color: '#0f172a', fontSize: 20, fontWeight: '700', letterSpacing: 0 },
  muted: { color: '#64748b', fontSize: 14, lineHeight: 20, marginTop: 4 },
  centerMuted: { color: '#64748b', fontSize: 13, lineHeight: 19, textAlign: 'center' },
  metrics: { flexDirection: 'row', gap: 10 },
  metric: { flex: 1, backgroundColor: '#f1f5f9', borderRadius: 8, padding: 12 },
  metricValue: { color: '#0f172a', fontSize: 24, fontWeight: '800' },
  metricLabel: { color: '#64748b', fontSize: 12, marginTop: 2 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  sectionTitle: { color: '#334155', fontSize: 13, fontWeight: '800', letterSpacing: 0, textTransform: 'uppercase', marginTop: 6 },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f0fdfa',
    borderWidth: 1,
    borderColor: '#99f6e4',
  },
  documentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 14,
    gap: 12,
  },
  rowIcon: { width: 42, height: 42, borderRadius: 8, backgroundColor: '#ccfbf1', alignItems: 'center', justifyContent: 'center' },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: { color: '#0f172a', fontSize: 16, fontWeight: '700', letterSpacing: 0 },
  rowSub: { color: '#64748b', fontSize: 14, lineHeight: 20, marginTop: 3 },
  activePill: { backgroundColor: '#0f766e', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  activePillText: { color: '#ffffff', fontSize: 12, fontWeight: '800' },
  inactivePill: { backgroundColor: '#e2e8f0' },
  inactivePillText: { color: '#475569' },
  primaryButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: '#0f766e',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
  },
  primaryButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#99f6e4',
    backgroundColor: '#f0fdfa',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
  },
  secondaryButtonText: { color: '#0f766e', fontSize: 16, fontWeight: '800' },
  dangerButton: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  dangerButtonText: { color: '#b91c1c', fontSize: 16, fontWeight: '800' },
  detailPanel: { backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1, borderColor: '#cbd5e1', padding: 16, gap: 10 },
  detailHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  infoLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e2e8f0',
  },
  infoLabel: { color: '#64748b', fontSize: 14 },
  infoValue: { color: '#0f172a', flex: 1, fontSize: 14, fontWeight: '600', textAlign: 'right' },
  statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingTop: 8 },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#f0fdfa', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 },
  statusText: { color: '#0f766e', fontSize: 12, fontWeight: '700' },
  panel: { backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1, borderColor: '#e2e8f0', padding: 16, gap: 8 },
  uploadBox: {
    minHeight: 78,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#99f6e4',
    backgroundColor: '#f0fdfa',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  toggleLine: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 14 },
  requestCard: { backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1, borderColor: '#fed7aa', padding: 14 },
  statusRequestText: { color: '#c2410c', fontSize: 13, fontWeight: '800', marginTop: 7 },
  approvedText: { color: '#0f766e' },
  deniedText: { color: '#b91c1c' },
  tinyText: { color: '#64748b', fontSize: 12, marginTop: 4 },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  smallPrimaryButton: { flex: 1, minHeight: 42, borderRadius: 8, backgroundColor: '#0f766e', alignItems: 'center', justifyContent: 'center' },
  smallPrimaryText: { color: '#ffffff', fontWeight: '800' },
  smallSecondaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallSecondaryText: { color: '#334155', fontWeight: '800' },
  contactCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  featureRow: { flexDirection: 'row', backgroundColor: '#ffffff', borderRadius: 8, borderWidth: 1, borderColor: '#e2e8f0', padding: 14, gap: 12 },
  featureText: { flex: 1, minWidth: 0 },
  inputLabel: { color: '#334155', fontSize: 13, fontWeight: '800', marginTop: 4, textTransform: 'uppercase' },
  input: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingHorizontal: 12,
    color: '#0f172a',
    fontSize: 16,
    backgroundColor: '#f8fafc',
  },
  segmented: { gap: 8 },
  segmentButton: { minHeight: 44, borderRadius: 8, borderWidth: 1, borderColor: '#cbd5e1', justifyContent: 'center', paddingHorizontal: 12, backgroundColor: '#ffffff' },
  segmentButtonActive: { backgroundColor: '#f0fdfa', borderColor: '#0f766e' },
  segmentText: { color: '#334155', fontWeight: '700' },
  segmentTextActive: { color: '#0f766e' },
  stateGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  stateButton: {
    width: '31.5%',
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  stateCode: { color: '#0f172a', fontSize: 15, fontWeight: '800' },
  stateName: { color: '#64748b', fontSize: 11, marginTop: 2 },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 76,
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    paddingBottom: 12,
  },
  tabButton: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 4 },
  tabLabel: { color: '#64748b', fontSize: 11, fontWeight: '700' },
  tabLabelActive: { color: '#0f766e' },
});
